[[entries]]
name = "[Exemple] Hello, world!"
script = "echo Hello, world!"

[[entries]]
name = "[Exemple] Echo argument"
script = "echo $1"
args = ["Text to print"]

[[entries]]
name = "[APT] Update packages"
script = "sudo apt update && sudo apt upgrade"

[[entries]]
name = "[Exemple] Install iforgor from current dir"
script = """
cargo install --path .
echo You should restart iforgor to use up-to-date binary.
"""
