[[entries]]
name = "[Exemple] Hello, world!"
script = "echo Hello, world!"

[[entries]]
name = "[Exemple] Echo argument"
script = "echo $1"
args = ["Text to print"]

[[entries]]
name = "[APT] Update packages"
script = "sudo apt update && sudo apt upgrade"

[[entries]]
name = "Force kill processes with interactive selection"
script = """
ps -x -o 'pid,pcpu,cmd' \
| tail -n +2 \
| while read id cpu cmd ; do echo "$id @ ($cpu %CPU) $cmd" ; done \
| ichoose --multi --title "Select processes to kill" \
| xargs kill -9
"""

[[entries]]
name = "[iforgor] Reload sources"
script = """
iforgor reload
echo
echo 🛑 Sources reloaded, you should restart iforgor to see up-to-date commands list
"""

[[entries]]
name = "[iforgor] Remove sources and reload"
script = """
iforgor source list \
| while read x ; do echo "$x @ $x" ; done \
| ichoose --multi --title "Select sources to delete" \
| while read x ; do iforgor source remove $x ; done
echo
echo 🛑 Sources deleted, you should restart iforgor to see up-to-date commands list
"""
